micronaut:
  application:
    name: fireholGateway
  http:
    client:
      max-content-length: 100000000
github:
  organization: firehol
  repo: blocklist-ipsets
  username: USERNAME
  token: TOKEN
elasticsearch:
  username: "admin"
  password: "admin"
  baseUrl: https://localhost:9200