micronaut:
  application:
    name: fireholGateway
  http:
    client:
      max-content-length: 1000000000
jackson:
  bean-introspection-module: true
github:
  organization: firehol
  repo: blocklist-ipsets
  username: username
  token: token
elasticsearch:
  username: "admin"
  password: "admin"
  baseUrl: https://localhost:9200
  maxBulkSize: 100000