micronaut:
  application:
    name: fireholGateway
github:
  organization: firehol
  repo: blocklist-ipsets
  username: USERNAME
  token: TOKEN
elasticsearch:
  username: "admin"
  password: "admin"
  baseUrl: https://localhost:9200